refactor: chart
alauda/chart pull request #15
Opened 2022-08-31 08:20 UTC by zChanges

2022-08-31 08:32 UTC, JounQin requested changes

2022-08-31 08:32 UTC, JounQin commented on src/components/index.ts
> +const LOADED_COMPONENTS: Map<string, CustomElementConstructor> = new Map();
个人不太建议用这种 global 的插件机制，这在比如 SSR 的场景下很容易出问题，个人推荐

```ts
const chart = createChart()

chart.register(name, plugin)
```

2022-08-31 08:32 UTC, JounQin commented on src/components/title.ts
> +    shadowRoot.innerHTML = `
用 DOM 操作避免用 `innerHTML`？

2022-08-31 08:32 UTC, JounQin commented on src/utils/dom.ts
>    ele: Element | HTMLElement,
```suggestion
  el: Element | HTMLElement,
```

2022-08-31 08:32 UTC, JounQin commented on src/utils/dom.ts
> +  return isNumber(+value) ? `${value}px` : value;
这种小函数看看能不能尽量避免用 lodash？

2022-08-31 09:00 UTC, zChanges commented on src/components/title.ts
> +    shadowRoot.innerHTML = `
嗯只是测试用的。后面会删掉

2022-08-31 09:01 UTC, zChanges commented on src/components/index.ts
> +const LOADED_COMPONENTS: Map<string, CustomElementConstructor> = new Map();
service 形式？

2022-08-31 09:05 UTC, JounQin commented on docs/chart.md
> +- immutable： chart 默认手动更新， data 支持 reactive 方式，内置 nextTick
应该是默认支持多次 `this.setData(data)` 批量操作在 nextTick 里生效吧，reactive 是指 `this.data = data`

2022-09-01 01:11 UTC, JounQin requested changes

2022-09-01 01:11 UTC, JounQin commented on src/index.ts
> +export const Component = new ComponentService();
你这样这个 Service 还是全局的，应该挂载在 chart 实例上？

2022-12-12 08:46 UTC, closed without merging